/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BankTransferDialog: typeof import('./components/payment/BankTransferDialog.vue')['default']
    BarChart: typeof import('./components/dashboard/BarChart.vue')['default']
    CardPaymentDialog: typeof import('./components/payment/CardPaymentDialog.vue')['default']
    Carousels: typeof import('./components/homepage/Carousels.vue')['default']
    CartList: typeof import('./components/CartList.vue')['default']
    ChatBox: typeof import('./components/ChatBox.vue')['default']
    EWalletDialog: typeof import('./components/payment/EWalletDialog.vue')['default']
    GlitchGif: typeof import('./components/homepage/GlitchGif.vue')['default']
    GMap: typeof import('./components/homepage/GMap.vue')['default']
    ItemCard: typeof import('./components/ItemCard.vue')['default']
    LineChart: typeof import('./components/dashboard/LineChart.vue')['default']
    LogoutButton: typeof import('./components/LogoutButton.vue')['default']
    Mapbox: typeof import('./components/homepage/Mapbox.vue')['default']
    OrderItemsTable: typeof import('./components/OrderItemsTable.vue')['default']
    OrderSummary: typeof import('./components/OrderSummary.vue')['default']
    PieChart: typeof import('./components/dashboard/PieChart.vue')['default']
    PlotlyGauge: typeof import('./components/dashboard/PlotlyGauge.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    SunburstChart: typeof import('./components/dashboard/SunburstChart.vue')['default']
    ThreeCanvas: typeof import('./components/ThreeCanvas.vue')['default']
    VueGauge: typeof import('./components/dashboard/VueGauge.vue')['default']
  }
}
